# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f954ee78be9897570e05fb26d2555986"
name = "3DLogistiX Integration"
handle = "3dlogistix-integration"
application_url = "https://api.3dlwms.com/dev/inventory/shopify/app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://api.3dlwms.com/dev/order/shopifywebhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "arn:aws:events:ap-southeast-2::event-source/aws.partner/shopify.com/247142842369/shopify_testing"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "https://api.3dlwms.com/dev/order/shopifywebhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "https://api.3dlwms.com/dev/order/shopifywebhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "https://api.3dlwms.com/dev/order/shopifywebhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, write_files, read_orders, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://api.3dlwms.com/dev/inventory/shopify/auth",
  "https://api.3dlwms.com/dev/inventory/shopify/auth/callback",
]

[pos]
embedded = false
