# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f954ee78be9897570e05fb26d2555986"
name = "3DLogistiX Integration"
handle = "3dlogistix-integration"
application_url = "https://risk-labour-consent-sacramento.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://risk-labour-consent-sacramento.trycloudflare.com/auth/callback",
  "https://risk-labour-consent-sacramento.trycloudflare.com/auth/shopify/callback",
  "https://risk-labour-consent-sacramento.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
